### ISSUE TITLE
Please Provide Flutter Examples using RxT<> and other Rx Collections.

### ISSUE THREAD

**Issue by ark-chatica** [DrDejaVuNG/flutter_super#3]
First of all, thank you for making this excellent library. I am doing some testing and I struggled to get RxT<> to work with my custom non-primitive objects. The issue I experienced is that the SuperBuilder seemingly did not detect changes to the state of RxT<> observables.  I am not sure if developers are meant to use SuperBuilder with these types... But SuperBuilder did work well with primitives such as "0.rx". 

Just a few more examples of this use case could be very helpful.

Thank you again !

**Comment by DrDejaVuNG** [comment]
Good day, Thank you for taking your time out to try the package!.

To solve the problem you're having, you have to mixin the SuperModel class with your Custom Type. E.g class BoxModel with SuperModel {}.

I am already working on more examples as well as full projects and they will be out soon. 👌

**Comment by DrDejaVuNG** [comment]
Also if you try any other feature you think should be working but isn't, take a look through that exact package's ReadMe as I have documented 95% of the APIs and how they can be used.

**Comment by ark-chatica** [comment]
Thank you so much for the reply. I just found the ReadMe and it is very helpful. And may I ask, with something like RxList, does that also require use of a SuperModel or is there a way to use RxList with SuperBuilder without any additional classes/extensions ?

**Comment by DrDejaVuNG** [comment]
If you're performing operations on the same list e.g myList = [].rx;, myList.add(1);, then no you don't need any extras, but if you intend to change a whole list at a go e.g myList = [1].Rx;, myList = [2] or [2].rx;, what you're doing is reassigning the variable, instead use an RxNotifier, that way you would be able to change the whole List at a go and if the items in the new list do not correspond with the items in the old list it will trigger a rebuild.

**Comment by ark-chatica** [comment]
Thanks, I'll give that a shot!

**Comment by DrDejaVuNG** [comment]
I made a mistake with my answer earlier, even when performing operations on the same list, it can not be used with a SuperBuilder and will result in an error, to fix this you should instead make use of the SuperConsumer widget as it allows you to specify the Rx object to watch. This is because the SuperBuilder can only watch Rx objects that have a .state property.

**Comment by DrDejaVuNG** [comment]
> If you're performing operations on the same list e.g myList = [].rx;, myList.add(1);, then no you don't need any extras, but if you intend to change a whole list at a go e.g myList = [1].Rx;, myList = [2] or [2].rx;, what you're doing is reassigning the variable, instead use an RxNotifier, that way you would be able to change the whole List at a go and if the items in the new list do not correspond with the items in the old list it will trigger a rebuild.

I made a mistake with my answer earlier, even when performing operations on the same list, it can not be used with a SuperBuilder and will result in an error, to fix this you should instead make use of the SuperConsumer widget as it allows you to specify the Rx object to watch. This is because the SuperBuilder can only watch Rx objects that have a .state property.
